export const blogPosts = [
  {
    slug: "troubleshooting-genesys-cloud-cx",
    category: "PRODUCTION SUPPORT",
    title: "How I Approach Troubleshooting in Genesys Cloud CX",
    excerpt:
      "A practical look at how I investigate production issues, narrow down possible causes, work with available evidence, and move toward resolution.",
    content: [
      "Production issues rarely arrive with a clear explanation of what went wrong. Usually, the first information available is a symptom: a call is not routing correctly, an IVR flow is behaving unexpectedly, customer context is missing, a campaign is not working as expected, or users are reporting inconsistent behavior.",
      "My first step is to understand the actual impact before trying to fix anything.",
      "I try to separate what is known from what is assumed. Which part of the interaction is failing? Is the issue affecting everyone or only specific scenarios? When did it begin? Was anything changed recently? Can the problem be reproduced?",
      "Once the scope is clearer, I follow the interaction through the relevant components. Depending on the issue, that may involve reviewing Genesys Cloud configurations, Architect flows, campaign behavior, telephony symptoms, integration data, logs, or other available evidence.",
      "I prefer narrowing the problem systematically instead of making multiple changes and hoping one of them works. Eliminating possibilities is an important part of troubleshooting.",
      "Logs and timestamps are especially useful when several systems are involved. Comparing events across platforms can help identify where expected behavior starts to break down.",
      "Not every issue can be solved independently. Some incidents require coordination with internal teams, client IT teams, or product support. In those situations, providing clear evidence, observations, and troubleshooting steps already performed makes collaboration much more effective.",
      "The biggest lesson I have learned is that troubleshooting is not about knowing every answer immediately. It is about asking the right questions, collecting evidence, reducing uncertainty, and continuing until the problem is understood well enough to move toward a reliable fix.",
    ],
    takeaways: [
      "Understand impact before attempting fixes.",
      "Separate evidence from assumptions.",
      "Narrow problems systematically.",
      "Use logs and timestamps to trace failures.",
      "Escalate with clear technical evidence.",
    ],
  },
  {
    slug: "automation-production-support",
    category: "ENGINEERING NOTES",
    title: "What Building Automation Taught Me About Production Support",
    excerpt:
      "Lessons from using PowerShell and lightweight automation to reduce repetitive work, improve visibility, and make troubleshooting more efficient.",
    content: [
      "Working in production support quickly shows how much engineering time can disappear into repetitive operational tasks.",
      "Checking the same services, collecting the same diagnostic information, monitoring recurring conditions, and performing routine recovery actions may be necessary, but doing everything manually does not always scale well.",
      "That is where I became interested in automation.",
      "I started looking for tasks that followed predictable steps and could be made more consistent using PowerShell and lightweight tooling.",
      "The first lesson I learned was that automation should solve a real operational problem. Automating something simply because it is possible can create more complexity than value.",
      "The second lesson was that visibility matters. A script that performs an action but provides no useful output, logging, or failure information becomes difficult to trust in a production environment.",
      "I also learned to think about failure conditions. What happens if a service does not respond? What if required data is unavailable? What if the script itself fails halfway through execution?",
      "These questions changed the way I approached automation. I began thinking beyond making scripts work and started thinking about making them understandable, maintainable, and useful during actual troubleshooting.",
      "Automation also improves consistency. A repeatable process can reduce missed steps and make diagnostic information easier to collect when time matters.",
      "The most important lesson has been that automation does not replace troubleshooting skills. Good automation supports engineers by removing unnecessary repetitive work and giving them better information.",
      "For me, the value of automation is simple: spend less time repeating predictable tasks and more time investigating problems that require engineering judgment.",
    ],
    takeaways: [
      "Automate real operational problems.",
      "Build visibility and failure handling into tooling.",
      "Prefer maintainable solutions over clever scripts.",
      "Use automation to improve consistency.",
      "Automation should support engineering judgment.",
    ],
  },
  {
    slug: "building-nexcx",
    category: "BUILDING NEXCX",
    title: "Why I Built NexCX and What I Learned Along the Way",
    excerpt:
      "The story behind turning contact center knowledge into practical calculators and an AI-assisted knowledge experience—and what building the project taught me.",
    content: [
      "NexCX started from a simple observation.",
      "While working with contact center technologies, I noticed that useful information was often spread across documentation, spreadsheets, formulas, notes, and different technical resources.",
      "I wanted to experiment with bringing some of that knowledge into one practical platform.",
      "That idea became NexCX.",
      "I started building enterprise contact center calculators for scenarios where engineers or teams may need quick estimates and structured inputs instead of repeatedly working through calculations manually.",
      "Later, I expanded the project with an AI-assisted knowledge experience focused on contact center technologies, including Genesys Cloud CX and Genesys Engage.",
      "Building NexCX pushed me outside my regular work responsibilities.",
      "I had to think about how information should be organized, how users would navigate the platform, how tools should behave, and how AI could be used without making the experience unreliable or unnecessarily complicated.",
      "I also used AI extensively during development. Not as a replacement for understanding what I was building, but as a way to explore ideas, debug problems, improve implementations, and learn technologies faster.",
      "One of the biggest lessons was that building a working product is very different from having an idea.",
      "Features that initially seemed useful sometimes needed to be simplified. Interfaces needed multiple iterations. Technical decisions had to be reconsidered when the actual user experience did not match what I imagined.",
      "The project is still evolving, and that is part of what makes it valuable to me.",
      "NexCX gave me a practical environment to combine contact center knowledge, AI experimentation, problem-solving, and product building.",
      "More importantly, it changed the way I learn. Instead of only studying technologies, I increasingly try to build something with them.",
    ],
    takeaways: [
      "Building reveals problems that ideas alone do not.",
      "Domain knowledge can become practical tools.",
      "AI is most useful when combined with understanding and judgment.",
      "Iteration and simplification improve products.",
      "Building projects creates deeper learning.",
    ],
  },
  {
    slug: "building-outside-day-job",
    category: "PERSONAL NOTES",
    title: "Why I Keep Building Things Outside My Day Job",
    excerpt:
      "My perspective on curiosity, continuous learning, experimenting with AI, helping others understand technical concepts, and turning ideas into practical projects.",
    content: [
      "My work gives me exposure to real technical problems, production environments, and responsibilities that require structured thinking.",
      "But my learning does not stop when the workday ends.",
      "I spend a significant amount of my personal time exploring AI tools, experimenting with ideas, building small applications, and understanding technologies that interest me.",
      "The reason is simple: I learn better when I create something.",
      "Reading documentation or watching tutorials can provide knowledge, but building forces me to make decisions, encounter problems, and find ways forward.",
      "AI has made this process even more interesting.",
      "I use AI as a learning and creative tool to explore unfamiliar topics, question my assumptions, improve ideas, and move from concepts toward working implementations.",
      "Sometimes the result is a complete project like NexCX. Other times it may be a small experiment, a website improvement, an automation idea, or simply a better understanding of how something works.",
      "I also enjoy explaining technical concepts and helping others when I understand something that may be useful to them. Teaching or discussing a topic often exposes gaps in my own understanding and pushes me to learn it more clearly.",
      "At the same time, I do not believe every hour needs to be productive.",
      "I enjoy action, thriller, and comedy movies, spending time with friends, and occasionally playing cricket. Those things give me space away from technical work and help me return with a clearer mind.",
      "I do not build things because I expect every experiment to become a product or business.",
      "I build because curiosity keeps me learning.",
      "Some ideas fail. Some remain unfinished. Others become useful projects.",
      "But each one teaches me something, and that is enough reason to keep building.",
    ],
    takeaways: [
      "Learning becomes deeper through building.",
      "AI can support creativity and independent learning.",
      "Teaching others improves understanding.",
      "Personal time does not need to be constantly productive.",
      "Curiosity is a strong reason to keep creating.",
    ],
  },
];
